config/routes.rb
Posty::Application.routes.draw do

  resources :users

  resources :topics

  resources :topics do
    resources :infos, only: [:index, :new, :create, :edit, :update, :delete, :destroy] do
      member do
        post 'demote'
        post 'promote'
      end
    end
  end

  resources :images # needed to find delete path for jquery-fileupload

  match '/signup',   to: 'users#new'
  root to: 'static_pages#home'

  resources :sessions, only: [:new, :create, :destroy]

  match '/signin',   to: 'sessions#new'
  match '/signout',  to: 'sessions#destroy', via: :delete

  resources :posts, only: [:create, :destroy, :index, :show]
  match '/newpost', to: 'posts#create'

end

app/models/info.rb
class Info < ActiveRecord::Base
  attr_accessible :child_of, :text, :title, :topic_id, :relative_layout, :images, :images_attributes
  belongs_to :topic
  has_many :images, :as => :imageable
  accepts_nested_attributes_for :images, allow_destroy: true, :reject_if => :all_blank

  include Rails.application.routes.url_helpers

  def to_jq_upload
  #  images.each{ |i| i.to_jq_json }
    images.each{ |i| i.as_json(:methods => :url_json) }

    # json = images.each{ |i| i.to_jq_json }
    # return json
    # json =images.each{ |i| i.to_json } # behaves the same as above

    # following does return to broswer, but not in correct JSON format
    # json_hash = {}
    # image_array = []
    # images.each{ |i|
    #   image_hash = {}
    #   image_hash["name"] = "test.jpg"
    #   image_hash["size"] = i.pic.size
    #   image_hash["url"] = i.pic.url(:original)
    #   image_array.push(image_hash)
    # }
    # json_hash["Object"] = image_array
    # json_hash.to_json
  end

end

app/controllers/infos_controller.rb
class InfosController < ApplicationController

  def new
    @topic = Topic.find(params[:topic_id])
    @info = Info.new
    @info.images.build
  end


  def create
    current_topic = Topic.find(params[:topic_id])
    @info = current_topic.infos.build(params[:info])
 #  @info = current_topic.infos.images.build(params[:info])

    @infos = current_topic.infos
    new_layout = 0

    if @info.child_of == nil then
      parents = []
      parents = @infos.reject{|i| !i.child_of.nil? }
      new_layout = parents.size
    else
      children = []
      children = @infos.reject{|i| i.child_of.nil? or i.child_of != @info.child_of }
      new_layout = children.size
    end

    @info.relative_layout = new_layout

    if @info.save
      #flash[:success] = 'Info paragraph created!'
      #redirect_to topic_infos_path

     respond_to do |format|

        # format.html {
        #   render :json => [@info.to_jq_upload].to_json,
        #   :content_type => 'text/html',
        #   :layout => false
        # }


        format.json { render json: [@info.images[0].as_json(  # must call on single image... at least to get working with example jq_upload code
                                                      :only => [:name],
                                                      :methods => [:url, :thumbnail_url, :delete_url, :delete_type, :size]
                                                         )] }





      end
    else
      #render action: "new"
     render :json => [{:error => "custom_failure"}], :status => 304
   end

  end

  def edit
  end

  def demote
    @topic = Topic.find(params[:topic_id])
    @info = Info.find(params[:id])

    current_layout = @info.relative_layout
    prospective_layout = current_layout + 1
    is_child_of = @info.child_of

    @neighbor = Info.find_by_child_of_and_relative_layout(is_child_of,prospective_layout)

    # If @info.child_of.nil? then the find above will behave with unpredictable results
    # So, we search for parental neighbors here:
    if @info.child_of.nil? then
      @infos = @topic.infos
      parents = @infos.reject{|i| !i.child_of.nil? }
      parents.sort_by!{ |x| x.relative_layout }
      parents.each{ |x| if x.relative_layout == prospective_layout then @neighbor = x end }
      end

    if (@neighbor != nil and
        @info.update_attributes(:relative_layout => prospective_layout) and
        @neighbor.update_attributes(:relative_layout => current_layout)
        )
      redirect_to topic_infos_path(@topic), notice: "Demotion succeeded. Moving:#{@info.id}"
    else
      redirect_to topic_infos_path(@topic), notice: "Demotion failed. Moving:#{@info.id}"
    end

  end


  def promote
    @topic = Topic.find(params[:topic_id])
    @info = Info.find(params[:id])

    current_layout = @info.relative_layout
    prospective_layout = current_layout - 1
    if prospective_layout < 0 then prospective_layout = 0 end

    is_child_of = @info.child_of

    @neighbor = Info.find_by_child_of_and_relative_layout(is_child_of,prospective_layout)

    # If @info.child_of.nil? then the find above will behave with unpredictable results
    # So, we search for parental neighbors here:
    if @info.child_of.nil? then
      @infos = @topic.infos
      parents = @infos.reject{|i| !i.child_of.nil? }
      parents.sort_by!{ |x| x.relative_layout }
      parents.each{ |x| if x.relative_layout == prospective_layout then @neighbor = x end }
      end

    if (@neighbor != nil and
        @info.update_attributes(:relative_layout => prospective_layout) and
        @neighbor.update_attributes(:relative_layout => current_layout)
        )
      redirect_to topic_infos_path(@topic), notice: "Promotion succeeded. Moving:#{@info.id}"
    else
      redirect_to topic_infos_path(@topic), notice: "Promotion failed. Moving:#{@info.id}"
    end

  end


  def index
    @topic = Topic.find(params[:topic_id])
    @infos = @topic.infos

    parents = []
    children = []

    @infos.each{ |i|
      if(i.child_of.nil?) then
        parents.push(i)
      else
        children.push(i)
      end
      }

    parents.sort_by!{|a| [a.relative_layout]}
    children.sort_by!{|a| [a.child_of,a.relative_layout] }

    @sorted_infos = []
    parents.each_with_index{ |p,px|
       if p.relative_layout != px then p.update_attributes(:relative_layout => px) end # repaired corruption from previous sorting regime
      @sorted_infos.push(p)
      children.each{ |c|
        if c.child_of == p.id then
          @sorted_infos.push(c)
      #    children.delete(c)
          end
      }
    }
  end

  def show
  end

  def info
  end

  def destroy
    @topic = Topic.find(params[:topic_id])
    @info = Info.find(params[:id])
    if @info.child_of != nil then # If we have a non-parent node.
      @info.destroy
    else                          # If we have a parent node we must check for children.
      @infos = @topic.infos
      @sorted_infos = @infos.sort_by{ |a| [a.relative_layout] }
      @child_count = @sorted_infos.count{|x| x.child_of == @info.id }
      if @sorted_infos.count{|x| x.child_of == @info.id } > 0 then
        flash[:failure] = "Could not delete! This item has #{@child_count} subitem(s)"
      else
        @info.destroy
      end
    end
    redirect_to topic_infos_path(@topic)
  end




end

app/helpers/infos_helper.rb
module InfosHelper
end

app/views/infos/_form.html.erb
<div class="container">

    <%= form_for [@topic, @info],  :html => { :multipart => true, :id => "fileupload"  } do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :text %>
    <%= f.text_area :text %>

    <br/>

    <div class="row fileupload-buttonbar">
      <div class="span7">
        <!-- The fileinput-button span is used to style the file input field as button -->
        <span class="btn btn-success fileinput-button">
          <i class="icon-plus icon-white"></i>
          <span>Add files...</span>
	  <%= f.fields_for :images do |builder| %>
          <%= builder.file_field :pic %>
	  <% end %>

        </span>
        <button type="submit" class="btn btn-primary start">
          <i class="icon-upload icon-white"></i>
          <span>Start upload</span>
        </button>
        <button type="reset" class="btn btn-warning cancel">
          <i class="icon-ban-circle icon-white"></i>
          <span>Cancel upload</span>
        </button>
        <button type="button" class="btn btn-danger delete">
          <i class="icon-trash icon-white"></i>
          <span>Delete</span>
        </button>
        <input type="checkbox" class="toggle">
      </div>
      <div class="span5">
        <!-- The global progress bar -->
        <div class="progress progress-success progress-striped active fade">
          <div class="bar" style="width:0%;"></div>
        </div>
      </div>
    </div>
    <!-- The loading indicator is shown during image processing -->
    <div class="fileupload-loading"></div>
    <br>

    <!-- The table listing the files available for upload/download -->
    <!-- <table class="table table-striped"><tbody class="files" data-toggle="modal-gallery" data-target="#modal-gallery"></tbody> -->
    <!-- </table> -->

    <!-- The table listing the files available for upload/download -->
    <table class="table table-striped"><tbody class="files"></tbody>
    </table>

  <!-- <div class="row"> -->
  <!--   <div class="span16"> -->
  <!--     <table class="zebra-striped"><tbody class="files"></tbody></table> -->
  <!--     <div id="loading"> </div> -->
  <!--   </div> -->
  <!-- </div> -->

    <%= f.submit class:"btn btn-primary"%> <%= link_to "Cancel", topic_infos_path(@topic, @info), class:"btn" %>
    <% end %>

</div>

<script>
  var fileUploadErrors = {
  maxFileSize: 'File is too big',
  minFileSize: 'File is too small',
  acceptFileTypes: 'Filetype not allowed',
  maxNumberOfFiles: 'Max number of files exceeded',
  uploadedBytes: 'Uploaded bytes exceed file size',
  emptyResult: 'Empty file upload result'
  };
</script>

<!-- The template to display files available for upload -->
<script id="template-upload" type="text/x-tmpl">
  {% for (var i=0, file; file=o.files[i]; i++) { %}
  <tr class="template-upload fade">
    <td class="preview"><span class="fade"></span></td>
    <td class="name"><span>{%=file.name%}</span></td>
    <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
    {% if (file.error) { %}
    <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
    {% } else if (o.files.valid && !i) { %}
    <td>
      <div class="progress progress-success progress-striped active"><div class="bar" style="width:0%;"></div></div>
    </td>
    <td class="start">{% if (!o.options.autoUpload) { %}
      <button class="btn btn-primary">
        <i class="icon-upload icon-white"></i>
        <span>{%=locale.fileupload.start%}</span>
      </button>
      {% } %}</td>
    {% } else { %}
    <td colspan="2"></td>
    {% } %}
    <td class="cancel">{% if (!i) { %}
      <button class="btn btn-warning">
        <i class="icon-ban-circle icon-white"></i>
        <span>{%=locale.fileupload.cancel%}</span>
      </button>
      {% } %}</td>
  </tr>
  {% } %}
</script>
<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
  {% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
      {% if (file.error) { %}
        <td></td>
        <td class="name"><span>{%=file.name%}</span></td>
        <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
        <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
        {% } else { %}
        <td class="preview">{% if (file.thumbnail_url) { %}
          <a href="{%=file.url%}" title="{%=file.name%}" rel="gallery" download="{%=file.name%}"><img src="{%=file.thumbnail_url%}"></a>
          {% } %}</td>
        <td class="name">
          <a href="{%=file.url%}" title="{%=file.name%}" rel="{%=file.thumbnail_url&&'gallery'%}" download="{%=file.name%}">{%=file.name%}</a>
        </td>
        <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
        <td colspan="2"></td>
        {% } %}
      <td class="delete">
        <button class="btn btn-danger" data-type="{%=file.delete_type%}" data-url="{%=file.delete_url%}">
          <i class="icon-trash icon-white"></i>
          <span>{%=locale.fileupload.destroy%}</span>
        </button>
        <input type="checkbox" name="delete" value="1">
      </td>
    </tr>
    {% } %}
</script>

<script type="text/javascript" charset="utf-8">
  $(function () {
      // Initialize the jQuery File Upload widget:
      $('#fileupload').fileupload();
      //
      // Load existing files:
      $.getJSON($('#fileupload').prop('action'), function (files) {
        var fu = $('#fileupload').data('fileupload'),
          template;
        fu._adjustMaxNumberOfFiles(-files.length);
        console.log(files);
        template = fu._renderDownload(files)
          .appendTo($('#fileupload .files'));
        // Force reflow:
        fu._reflow = fu._transition && template.length &&
          template[0].offsetWidth;
        template.addClass('in');
        $('#loading').remove();
      });

  });
</script>

app/views/infos/_image_fields.html.erb
<!-- <p> -->
<!--   <%= f.label :name, "Image Name" %><br /> -->
<!--   <%= f.text_field :name %><br /> -->
<!--   <%= f.label :description, "Image Description" %><br /> -->
<!--   <%= f.text_field :description %><br /> -->
<!--   <%= f.label :pic %><br /> -->
<!--   <%= f.file_field :pic %><br /> -->
<!-- </p> -->

<div class="container">
    <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
    <div class="row fileupload-buttonbar">
      <div class="span7">
        <!-- The fileinput-button span is used to style the file input field as button -->
        <span class="btn btn-success fileinput-button">
          <i class="icon-plus icon-white"></i>
          <span>Add files...</span>
          <%= f.file_field :pic %>
        </span>
        <button type="submit" class="btn btn-primary start">
          <i class="icon-upload icon-white"></i>
          <span>Start upload</span>
        </button>
        <button type="reset" class="btn btn-warning cancel">
          <i class="icon-ban-circle icon-white"></i>
          <span>Cancel upload</span>
        </button>
        <button type="button" class="btn btn-danger delete">
          <i class="icon-trash icon-white"></i>
          <span>Delete</span>
        </button>
        <input type="checkbox" class="toggle">
      </div>
      <div class="span5">
        <!-- The global progress bar -->
        <div class="progress progress-success progress-striped active fade">
          <div class="bar" style="width:0%;"></div>
        </div>
      </div>
    </div>
    <!-- The loading indicator is shown during image processing -->
    <div class="fileupload-loading"></div>
    <br>
    <!-- The table listing the files available for upload/download -->
    <table class="table table-striped"><tbody class="files" data-toggle="modal-gallery" data-target="#modal-gallery"></tbody>
    </table>
</div>
<script>
  var fileUploadErrors = {
  maxFileSize: 'File is too big',
  minFileSize: 'File is too small',
  acceptFileTypes: 'Filetype not allowed',
  maxNumberOfFiles: 'Max number of files exceeded',
  uploadedBytes: 'Uploaded bytes exceed file size',
  emptyResult: 'Empty file upload result'
  };
</script>

<!-- The template to display files available for upload -->
<script id="template-upload" type="text/x-tmpl">
  {% for (var i=0, file; file=o.files[i]; i++) { %}
  <tr class="template-upload fade">
    <td class="preview"><span class="fade"></span></td>
    <td class="name"><span>{%=file.name%}</span></td>
    <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
    {% if (file.error) { %}
    <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
    {% } else if (o.files.valid && !i) { %}
    <td>
      <div class="progress progress-success progress-striped active"><div class="bar" style="width:0%;"></div></div>
    </td>
    <td class="start">{% if (!o.options.autoUpload) { %}
      <button class="btn btn-primary">
        <i class="icon-upload icon-white"></i>
        <span>{%=locale.fileupload.start%}</span>
      </button>
      {% } %}</td>
    {% } else { %}
    <td colspan="2"></td>
    {% } %}
    <td class="cancel">{% if (!i) { %}
      <button class="btn btn-warning">
        <i class="icon-ban-circle icon-white"></i>
        <span>{%=locale.fileupload.cancel%}</span>
      </button>
      {% } %}</td>
  </tr>
  {% } %}
</script>
<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
  {% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
      {% if (file.error) { %}
        <td></td>
        <td class="name"><span>{%=file.name%}</span></td>
        <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
        <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
        {% } else { %}
        <td class="preview">{% if (file.thumbnail_url) { %}
          <a href="{%=file.url%}" title="{%=file.name%}" rel="gallery" download="{%=file.name%}"><img src="{%=file.thumbnail_url%}"></a>
          {% } %}</td>
        <td class="name">
          <a href="{%=file.url%}" title="{%=file.name%}" rel="{%=file.thumbnail_url&&'gallery'%}" download="{%=file.name%}">{%=file.name%}</a>
        </td>
        <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
        <td colspan="2"></td>
        {% } %}
      <td class="delete">
        <button class="btn btn-danger" data-type="{%=file.delete_type%}" data-url="{%=file.delete_url%}">
          <i class="icon-trash icon-white"></i>
          <span>{%=locale.fileupload.destroy%}</span>
        </button>
        <input type="checkbox" name="delete" value="1">
      </td>
    </tr>
    {% } %}
</script>

<script type="text/javascript" charset="utf-8">
  $(function () {
      // Initialize the jQuery File Upload widget:
      $('#fileupload').fileupload();
      //
      // Load existing files:
      $.getJSON($('#fileupload').prop('action'), function (files) {
        var fu = $('#fileupload').data('fileupload'),
          template;
        fu._adjustMaxNumberOfFiles(-files.length);
        console.log(files);
        template = fu._renderDownload(files)
          .appendTo($('#fileupload .files'));
        // Force reflow:
        fu._reflow = fu._transition && template.length &&
          template[0].offsetWidth;
        template.addClass('in');
        $('#loading').remove();
      });

  });
</script>

app/views/infos/create.html.erb
<h1>Infos#create</h1>
<p>Find me in app/views/infos/create.html.erb</p>

app/views/infos/destroy.html.erb
<h1>Infos#destroy</h1>
<p>Find me in app/views/infos/destroy.html.erb</p>

app/views/infos/edit.html.erb
<h1>Infos#edit</h1>
<p>Find me in app/views/infos/edit.html.erb</p>

app/views/infos/index.html.erb
<h1>
<% if @topic.name.split(' ').size < 2  %>
<%= @topic.name.pluralize %>
<% else %>
<%= @topic.name %>
<% end %>
</h1>

<span class="center">
  <p>There are <%= @infos.size %> entries on <%= @topic.name %>  <em> (<%= @topic.systematic_name %>) </em> </p>
  <% if signed_in? and (current_user.has_role? :admin) %>
  <p> <%= link_to 'Add new info paragraph', new_topic_info_path(@topic), class:'btn btn-info' %></p>
  <% end %>
</span>
<% @sorted_infos.each do |i| %>
<% if i.child_of.nil? then %>
<div class="container">
    <ol class="infos">
      <h2><%= i.title %></h2>

      <% if signed_in? %>
      <div class="btn-group">
	<a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
	  Action
	  <span class="caret"></span>
	</a>
	<ul class="dropdown-menu">
	    <%= link_to 'Add sub info', new_topic_info_path(@topic,child_of:i) %>
	    <%= link_to "Delete info", { :action => "destroy", :id => i.id }, :confirm => "Are you sure?", :method => :delete %>
	</ul>
      </div>

	  <span class="buttons">
	    <% if i.relative_layout > 0 then %>
	    <%= button_to '+', promote_topic_info_path(@topic,i), class:'btn btn-mini'  %>
	    <% end %>
	    <%= button_to '-', demote_topic_info_path(@topic,i), class:'btn btn-mini'  %>
	  </span>
	  <% end %>

      <li></li>

      <% pics = i.images %>
      <% pics.each do |p| %>
      <p><%=  p.name  %></p>
      <%= link_to (image_tag p.pic.url(:medium)), p.pic.url(:large)  %>
      <% end %>

<p><%= i.text %></p>
	<% if signed_in? %>
	  </br><p><small>id: <%= i.id %> layout: <%= i.relative_layout %> child_count: <%= @sorted_infos.count{|x| x.child_of == i.id } %> child_of: <%= i.child_of %></small></p>
	  <% end %>

    </ol>
</div>
<% else %>
<div class="container">
    <ol class="subinfos">
      <h3><%= i.title %></h3>

      <% if signed_in? %>
      <span class="buttons">
	    <% if i.relative_layout > 0 then %>
      	<%= button_to '+', promote_topic_info_path(@topic,i),class:'btn'%>
	    <% end %>
      	<%= button_to '-', demote_topic_info_path(@topic,i), class:'btn'%>
      	<%= button_to "Delete", { :action => "destroy", :id => i.id }, :confirm => "Are you sure?", :method => :delete, class:'btn-danger' %>
      	</span>
      <% end %>

      <li></li>
      <% pics = i.images %>
      <% pics.each do |p| %>
      <p><%=  p.name  %></p
      <%= link_to (image_tag p.pic.url(:medium)), p.pic.url(:large)  %>
      <% end %>
	<p><%= i.text %></p>
	<% if signed_in? %>
	<p><small>id: <%= i.id %> layout: <%= i.relative_layout %> child_count: <%= @sorted_infos.count{|x| x.child_of == i.id } %> child_of: <%= i.child_of %></small></p>
	<% end %>
    </ol>

</div>
<% end %>
<% end %>

app/views/infos/info.html.erb
<h1>Infos#info</h1>
<p>Find me in app/views/infos/info.html.erb</p>

app/views/infos/new.html.erb
<h1>New info</h1>

<%= render 'form' %>

app/views/infos/show.html.erb
<h1>Infos#show</h1>
<p>Find me in app/views/infos/show.html.erb</p>